version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/audio_service
      SECRET_KEY: your-secret-key
      YANDEX_CLIENT_ID: your-yandex-client-id
      YANDEX_CLIENT_SECRET: your-yandex-client-secret
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audio_service
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
